import { ArrowRight, Check, Code2, Globe2, Layers3, Moon, Sun, Smartphone, ShoppingBag, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useTheme } from "@/contexts/ThemeContext";
import { useLanguage } from "@/contexts/LanguageContext";

const mark = "/manus-storage/snowcode-mark_2b5b9404.png";

type Service = { icon: typeof Code2; enTitle: string; arTitle: string; enBody: string; arBody: string; points: string[] };
const services: Service[] = [
  { icon: Globe2, enTitle: "Websites & digital experiences", arTitle: "المواقع والتجارب الرقمية", enBody: "Fast, focused websites that make your brand clearer and your next action easier.", arBody: "مواقع سريعة وواضحة تجعل علامتك التجارية أقوى وتجعل الخطوة التالية أسهل للزائر.", points: ["Strategy and information architecture", "Responsive UI design", "Production-ready React development"] },
  { icon: Smartphone, enTitle: "Mobile applications", arTitle: "تطبيقات الهاتف", enBody: "Useful mobile products designed around real habits, from first prototype to reliable release.", arBody: "منتجات هاتف مفيدة مصممة حول احتياجات المستخدم الحقيقية، من النموذج الأولي إلى الإطلاق.", points: ["iOS and Android product flows", "Prototype and interaction design", "Scalable app foundations"] },
  { icon: ShoppingBag, enTitle: "E-commerce platforms", arTitle: "منصات التجارة الإلكترونية", enBody: "Confident shopping journeys that turn complex catalogs into simple decisions and repeat customers.", arBody: "رحلات شراء سهلة تحول الكتالوجات المعقدة إلى قرارات بسيطة وعملاء متكررين.", points: ["Storefront and checkout UX", "Catalog and content systems", "Conversion-minded interfaces"] },
  { icon: Layers3, enTitle: "Internal tools & platforms", arTitle: "المنصات والأدوات الداخلية", enBody: "Calm systems for teams that need better visibility, smoother operations, and less noise.", arBody: "أنظمة هادئة للفرق التي تحتاج رؤية أفضل وتشغيلاً أسلس وضوضاء أقل.", points: ["Dashboards and workflows", "Role-based admin experiences", "Data and API integrations"] },
  { icon: Sparkles, enTitle: "Brand systems & UI", arTitle: "أنظمة الهوية وواجهات المستخدم", enBody: "A visual language that gives every screen, message, and interaction the same confident voice.", arBody: "لغة بصرية تمنح كل شاشة ورسالة وتفاعل صوتًا موحدًا وواثقًا.", points: ["Visual direction and identity", "Design systems and components", "Content-ready brand guidance"] },
  { icon: Code2, enTitle: "Ongoing product support", arTitle: "الدعم والتطوير المستمر", enBody: "Thoughtful iteration after launch: improvements, maintenance, and the next useful feature.", arBody: "تطوير مستمر بعد الإطلاق: تحسينات وصيانة وإضافة الميزة المفيدة التالية.", points: ["Performance and accessibility", "Feature planning and delivery", "Reliable technical maintenance"] },
];

export default function Services() {
  const { theme, toggleTheme } = useTheme();
  const { isArabic: arabic, toggleLanguage } = useLanguage();
  return <div className={`services-page ${arabic ? "services-ar" : ""}`} dir={arabic ? "rtl" : "ltr"}>
    <header className="services-nav"><Link href="/" className="services-brand"><img src={mark} alt="SnowCode" /><span><strong>Snow<span>Code</span></strong><small>BUILD · CODE · GROW</small></span></Link><nav><Link href="/">{arabic ? "الرئيسية" : "Home"}</Link><a href="#services">{arabic ? "الخدمات" : "Services"}</a><a href="/#contact">{arabic ? "تواصل" : "Contact"}</a><button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle theme">{theme === "dark" ? <Sun size={16} /> : <Moon size={16} />}</button><button className="language-toggle" onClick={toggleLanguage}>{arabic ? "EN" : "عربي"}</button></nav></header>
    <main>
      <section className="services-hero"><span className="services-kicker">SnowCode · {arabic ? "خدمات رقمية" : "digital services"}</span><h1>{arabic ? <>نبني منتجات<br /><em>تنمو معك.</em></> : <>Build products<br /><em>that move you forward.</em></>}</h1><p>{arabic ? "من الفكرة إلى الإطلاق، نساعد الفرق الطموحة على تحويل المشاكل المعقدة إلى تجارب رقمية مفيدة." : "From the first idea to the next release, we help ambitious teams turn complex problems into useful digital experiences."}</p><a className="services-cta" href="/#contact">{arabic ? "ابدأ محادثة" : "Start a conversation"} <ArrowRight size={16} /></a></section>
      <section className="services-grid" id="services">{services.map(({ icon: Icon, enTitle, arTitle, enBody, arBody, points }) => <article className="service-detail" key={enTitle}><div className="service-icon"><Icon size={22} /></div><span className="service-index">0{services.indexOf(services.find((item) => item.enTitle === enTitle)!) + 1}</span><h2>{arabic ? arTitle : enTitle}</h2><p>{arabic ? arBody : enBody}</p><ul>{points.map((point) => <li key={point}><Check size={14} />{arabic ? ({ "Strategy and information architecture": "الاستراتيجية وهيكلة المحتوى", "Responsive UI design": "تصميم واجهات متجاوبة", "Production-ready React development": "تطوير React جاهز للإنتاج", "iOS and Android product flows": "تجارب iOS وAndroid", "Prototype and interaction design": "النمذجة وتصميم التفاعل", "Scalable app foundations": "بنية تطبيق قابلة للتوسع", "Storefront and checkout UX": "تجربة المتجر والدفع", "Catalog and content systems": "أنظمة الكتالوج والمحتوى", "Conversion-minded interfaces": "واجهات تركز على التحويل", "Dashboards and workflows": "لوحات التحكم وسير العمل", "Role-based admin experiences": "تجارب إدارة حسب الصلاحيات", "Data and API integrations": "تكاملات البيانات وواجهات API", "Visual direction and identity": "التوجيه البصري والهوية", "Design systems and components": "أنظمة التصميم والمكونات", "Content-ready brand guidance": "إرشادات هوية جاهزة للمحتوى", "Performance and accessibility": "الأداء وسهولة الوصول", "Feature planning and delivery": "تخطيط وتسليم الميزات", "Reliable technical maintenance": "صيانة تقنية موثوقة" } as Record<string, string>)[point] : point}</li>)}</ul></article>)}</section>
      <section className="services-bottom"><div><span className="services-kicker">{arabic ? "هل لديك فكرة؟" : "Have a good one?"}</span><h2>{arabic ? "لنبنِ شيئًا مفيدًا." : "Let’s make something useful."}</h2></div><a className="services-cta" href="/#contact">{arabic ? "تواصل مع الفريق" : "Talk to the team"} <ArrowRight size={16} /></a></section>
    </main>
    <footer className="services-footer"><span>© 2026 SnowCode Team</span><Link href="/">{arabic ? "العودة للموقع" : "Back to site"}</Link></footer>
  </div>;
}
